@extends('layouts.master')

@section('content')
    <body>
        <div class="flex-center position-ref full-height">
            @if (Route::has('login'))
                <div class="top-right links">
                    @auth
                        <a href="{{ url('/home') }}">Home</a>
                    @else
                        <a href="{{ route('login') }}">Login</a>
                        <a href="{{ route('register') }}">Register</a>
                    @endauth
                </div>
            @endif

            <div class="content">
                <div class="title m-b-md">
                    Laravel
                </div>

                <div class="links">
                    <a href="https://laravel.com/docs">Documentation</a>
                    <a href="https://laracasts.com">Laracasts</a>
                    <a href="https://laravel-news.com">News</a>
                    <a href="https://forge.laravel.com">Forge</a>
                    <a href="https://github.com/laravel/laravel">GitHub</a>
                </div>

                <p>
                    I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to speak on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk.

But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong.

Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text below. Don't bother to read the words. They're just the text you are already reading.

Don't read this sample big, bad paragraph--just notice it. 
I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to talk on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk. But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong. Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text here. I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource.I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to talk on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk. But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong. Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text here I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource.

I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression of thoughts stuffed into one big paragraph. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource. I won't be attending that meeting.

A huge block of text, even when well organized, intimidates readers and turns off skimmers. Most of us know this, but if you work with people who are still churning out thick wads of text, talk with them about what works in today's messages. You will be doing your coworkers--and their readers--a huge favor.I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to speak on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk.

But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong.

Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text below. Don't bother to read the words. They're just the text you are already reading.

Don't read this sample big, bad paragraph--just notice it. 
I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to talk on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk. But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong. Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text here. I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource.I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to talk on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk. But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong. Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text here I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource.

I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression of thoughts stuffed into one big paragraph. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource. I won't be attending that meeting.

A huge block of text, even when well organized, intimidates readers and turns off skimmers. Most of us know this, but if you work with people who are still churning out thick wads of text, talk with them about what works in today's messages. You will be doing your coworkers--and their readers--a huge favor.I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to speak on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk.

But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong.

Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text below. Don't bother to read the words. They're just the text you are already reading.

Don't read this sample big, bad paragraph--just notice it. 
I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to talk on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk. But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong. Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text here. I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource.I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to talk on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk. But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong. Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text here I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource.

I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression of thoughts stuffed into one big paragraph. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource. I won't be attending that meeting.

A huge block of text, even when well organized, intimidates readers and turns off skimmers. Most of us know this, but if you work with people who are still churning out thick wads of text, talk with them about what works in today's messages. You will be doing your coworkers--and their readers--a huge favor.I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to speak on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk.

But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong.

Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text below. Don't bother to read the words. They're just the text you are already reading.

Don't read this sample big, bad paragraph--just notice it. 
I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to talk on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk. But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong. Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text here. I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource.I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to talk on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk. But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong. Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text here I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource.

I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression of thoughts stuffed into one big paragraph. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource. I won't be attending that meeting.

A huge block of text, even when well organized, intimidates readers and turns off skimmers. Most of us know this, but if you work with people who are still churning out thick wads of text, talk with them about what works in today's messages. You will be doing your coworkers--and their readers--a huge favor.I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to speak on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk.

But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong.

Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text below. Don't bother to read the words. They're just the text you are already reading.

Don't read this sample big, bad paragraph--just notice it. 
I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to talk on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk. But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong. Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text here. I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource.I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to talk on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk. But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong. Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text here I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource.

I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression of thoughts stuffed into one big paragraph. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource. I won't be attending that meeting.

A huge block of text, even when well organized, intimidates readers and turns off skimmers. Most of us know this, but if you work with people who are still churning out thick wads of text, talk with them about what works in today's messages. You will be doing your coworkers--and their readers--a huge favor.I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to speak on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk.

But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong.

Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text below. Don't bother to read the words. They're just the text you are already reading.

Don't read this sample big, bad paragraph--just notice it. 
I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to talk on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk. But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong. Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text here. I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource.I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to talk on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk. But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong. Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text here I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource.

I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression of thoughts stuffed into one big paragraph. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource. I won't be attending that meeting.

A huge block of text, even when well organized, intimidates readers and turns off skimmers. Most of us know this, but if you work with people who are still churning out thick wads of text, talk with them about what works in today's messages. You will be doing your coworkers--and their readers--a huge favor.I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to speak on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk.

But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong.

Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text below. Don't bother to read the words. They're just the text you are already reading.

Don't read this sample big, bad paragraph--just notice it. 
I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to talk on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk. But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong. Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text here. I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource.I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to talk on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk. But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong. Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text here I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource.

I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression of thoughts stuffed into one big paragraph. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource. I won't be attending that meeting.

A huge block of text, even when well organized, intimidates readers and turns off skimmers. Most of us know this, but if you work with people who are still churning out thick wads of text, talk with them about what works in today's messages. You will be doing your coworkers--and their readers--a huge favor.I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to speak on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk.

But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong.

Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text below. Don't bother to read the words. They're just the text you are already reading.

Don't read this sample big, bad paragraph--just notice it. 
I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to talk on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk. But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong. Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text here. I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource.I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to talk on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk. But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong. Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text here I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource.

I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression of thoughts stuffed into one big paragraph. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource. I won't be attending that meeting.

A huge block of text, even when well organized, intimidates readers and turns off skimmers. Most of us know this, but if you work with people who are still churning out thick wads of text, talk with them about what works in today's messages. You will be doing your coworkers--and their readers--a huge favor.I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to speak on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk.

But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong.

Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text below. Don't bother to read the words. They're just the text you are already reading.

Don't read this sample big, bad paragraph--just notice it. 
I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to talk on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk. But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong. Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text here. I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource.I was reading the list of upcoming business meetings in a weekly email from The Seattle Times, when a meeting announcement caught my attention. The presenter was going to talk on a topic that interests me--the steps in growing one's business. I often weigh the advantages of getting bigger vs. staying small as a business, so I thought I would register for her talk. But I wanted to know more about the presenter, so I clicked the link to her blog. That's when things went wrong. Her latest blog entry was one huge paragraph 41 lines long. Can you imagine her 325 words in one big block? You don't have to--I have created a 325-word block of text here I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource.

I forced myself to read her paragraph. Hiding in it was some good information, but that info could not undo the negative impression of thoughts stuffed into one big paragraph. If that big, bad paragraph represents the woman's communication skills, I would be much better off finding another resource. I won't be attending that meeting.

A huge block of text, even when well organized, intimidates readers and turns off skimmers. Most of us know this, but if you work with people who are still churning out thick wads of text, talk with them about what works in today's messages. You will be doing your coworkers--and their readers--a huge favor.
                </p>
            </div>
        </div>
    </body>
    <!-- /.container -->

@endsection


