<?php

use Illuminate\Database\Seeder;

class ThanaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $thanas = [
            ['district_id'=>'1', 'thana_name'=>'ডেমরা', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'1', 'thana_name'=>'ঢাকা ক্যান্ট', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'1', 'thana_name'=>'ধামরাই', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'1', 'thana_name'=>'ধনমণ্ডি', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'1', 'thana_name'=>'গুলশান', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'1', 'thana_name'=>'যাত্রবাড়ী', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'1', 'thana_name'=>'জয়পাড়া', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'1', 'thana_name'=>'কেরানীগঞ্জ', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'1', 'thana_name'=>'খিলগাঁও', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'1', 'thana_name'=>'খিলক্ষেত', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'1', 'thana_name'=>'লালবাগ', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'1', 'thana_name'=>'মিরপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'1', 'thana_name'=>'মোহাম্মদপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'1', 'thana_name'=>'মতিঝিল', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'1', 'thana_name'=>'নবাবগঞ্জ', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'1', 'thana_name'=>'নতুন বাজার', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'1', 'thana_name'=>'পল্টন', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'1', 'thana_name'=>'রমনা', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'1', 'thana_name'=>'সবুজবাগ', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'1', 'thana_name'=>'সাভার', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'1', 'thana_name'=>'সূত্রাপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'1', 'thana_name'=>'তেজগাঁও', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'1', 'thana_name'=>'উত্তরা', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'2', 'thana_name'=>'আলফাদাঙ্গা', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'2', 'thana_name'=>'ভাগা', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'2', 'thana_name'=>'বোয়ালমারি', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'2', 'thana_name'=>'চারভূষণ', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'2', 'thana_name'=>'ফরিদপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'2', 'thana_name'=>'মাধুখালী', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'2', 'thana_name'=>'নাগার্কন্দ', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'2', 'thana_name'=>'সদরপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'2', 'thana_name'=>'শ্রিয়ানগন', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'2', 'thana_name'=>'শ্রীনগর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'3', 'thana_name'=>'গাজীপুর সদর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'3', 'thana_name'=>'কালিয়াকাকার', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'3', 'thana_name'=>'কালীগঞ্জ', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'3', 'thana_name'=>'কাপাশিয়া', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'3', 'thana_name'=>'মননুনগর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'3', 'thana_name'=>'শ্রীপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'4', 'thana_name'=>'গোপালগঞ্জ সদর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'4', 'thana_name'=>'কাশিয়ানী', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'4', 'thana_name'=>'কোটালিপাড়া', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'4', 'thana_name'=>'মাকসুদপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'4', 'thana_name'=>'তুঙ্গিপাড়া', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'5', 'thana_name'=>'বাজিতপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'5', 'thana_name'=>'ভৈরব', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'5', 'thana_name'=>'হোসেনপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'5', 'thana_name'=>'ইটনা', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'5', 'thana_name'=>'করিমগঞ্জ', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'5', 'thana_name'=>'কাতাদি', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'5', 'thana_name'=>'কিশোরগঞ্জ সদর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'5', 'thana_name'=>'কুলিয়ারচর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'5', 'thana_name'=>'মিঠামাইন', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'5', 'thana_name'=>'নিকলি', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'5', 'thana_name'=>'ওস্তগ্রাম', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'5', 'thana_name'=>'পাকুন্ডিয়া', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'5', 'thana_name'=>'তারিয়াল', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'6', 'thana_name'=>'বরামগঞ্জ', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'6', 'thana_name'=>'কলকিনি', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'6', 'thana_name'=>'মাদারীপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'6', 'thana_name'=>'রাজোইর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'7', 'thana_name'=>'দৌলতপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'7', 'thana_name'=>'ঘিয়র', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'7', 'thana_name'=>'লেচ্রাগঞ্জ', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'7', 'thana_name'=>'মানিকগঞ্জ সদর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'7', 'thana_name'=>'সাতুরিয়া', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'7', 'thana_name'=>'শিবলোয়া', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'7', 'thana_name'=>'সিংড়ি', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'8', 'thana_name'=>'গজারিয়া', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'8', 'thana_name'=>'লোহজং', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'8', 'thana_name'=>'মুন্সীগঞ্জ সদর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'8', 'thana_name'=>'সিরাজদিখান', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'8', 'thana_name'=>'শ্রীনগর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'9', 'thana_name'=>'আরিহাজার', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'9', 'thana_name'=>'বাইদদার বাজার', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'9', 'thana_name'=>'বন্দর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'9', 'thana_name'=>'ফাতুল্লাহ', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'9', 'thana_name'=>'নারায়ণগঞ্জ সদর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'9', 'thana_name'=>'রূপগঞ্জ', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'9', 'thana_name'=>'সিদ্ধিরগঞ্জ', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'10', 'thana_name'=>'বেলবো', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'10', 'thana_name'=>'মনহোর্দি', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'10', 'thana_name'=>'নরসিংদী সদর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'10', 'thana_name'=>'পলাশ', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'10', 'thana_name'=>'রায়পুরা', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'10', 'thana_name'=>'শিবিপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'11', 'thana_name'=>'বালিয়াকান্দি', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'11', 'thana_name'=>'পাংশা', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'11', 'thana_name'=>'রাজবাড়ী সদর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'11', 'thana_name'=>'ভেদরগঞ্জ', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'11', 'thana_name'=>'দামুধা', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'11', 'thana_name'=>'গোসাইয়ারহাট', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'11', 'thana_name'=>'জাজিরা', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'11', 'thana_name'=>'নারিয়া', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'11', 'thana_name'=>'শরিয়তপুর সদর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'13', 'thana_name'=>'বাসাইল', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'13', 'thana_name'=>'ভুয়াপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'13', 'thana_name'=>'ডেলদুয়ার', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'13', 'thana_name'=>'ঘাটাইল', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'13', 'thana_name'=>'গোপালপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'13', 'thana_name'=>'কালিহতী', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'13', 'thana_name'=>'কাশকোলিয়া', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'13', 'thana_name'=>'মধুপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'13', 'thana_name'=>'মির্জাপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'13', 'thana_name'=>'নগরপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'13', 'thana_name'=>'সখীপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'13', 'thana_name'=>'টাঙ্গাইল সদর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'14', 'thana_name'=>'দেওয়ানগঞ্জ', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'14', 'thana_name'=>'ইসলামপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'14', 'thana_name'=>'জামালপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'14', 'thana_name'=>'মালান্ডা', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'14', 'thana_name'=>'মাদারগঞ্জ', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'14', 'thana_name'=>'শরিশবাড়ী', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'15', 'thana_name'=>'ভলুকু', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'15', 'thana_name'=>'ফুলবারিয়া', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'15', 'thana_name'=>'গফরগাঁও', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'15', 'thana_name'=>'গৌরীপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'15', 'thana_name'=>'হালুয়াঘাট', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'15', 'thana_name'=>'ইশবার্গঞ্জ', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'15', 'thana_name'=>'মুক্তগাছা', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'15', 'thana_name'=>'ময়মনসিংহ সদর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'15', 'thana_name'=>'নন্দাইল', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'15', 'thana_name'=>'ফুলপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'15', 'thana_name'=>'ত্রিশাল', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'16', 'thana_name'=>'সুসঙ্গ দুর্গাপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'16', 'thana_name'=>'আটপারা', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'16', 'thana_name'=>'বারহট্ট', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'16', 'thana_name'=>'ধর্মপাশা', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'16', 'thana_name'=>'ধোবৌরা', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'16', 'thana_name'=>'কলমকন্দ', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'16', 'thana_name'=>'কেঁদুয়া', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'16', 'thana_name'=>'খালিয়াজুরি', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'16', 'thana_name'=>'মাদান', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'16', 'thana_name'=>'মডধীনগর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'16', 'thana_name'=>'মোহনগঞ্জ', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'16', 'thana_name'=>'নেত্রকোনা সদর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'16', 'thana_name'=>'পূর্বাধলা', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'17', 'thana_name'=>'বাকশিগঞ্জ', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'17', 'thana_name'=>'ঝিনাইগতি', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'17', 'thana_name'=>'নকলা', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'17', 'thana_name'=>'নলিতাবাড়ি', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'17', 'thana_name'=>'শেরপুর সদর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'17', 'thana_name'=>'শ্রীবরদী', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'45', 'thana_name'=>'আজমিরিগঞ্জ', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'45', 'thana_name'=>'বাহুবল', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'45', 'thana_name'=>'বানিয়াংচ', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'45', 'thana_name'=>'চুনারুঘাট', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'45', 'thana_name'=>'হবিগঞ্জ সদর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'45', 'thana_name'=>'কালউক', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'45', 'thana_name'=>'মাধবপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'45', 'thana_name'=>'নববীগঞ্জ', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'46', 'thana_name'=>'বারলেখা', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'46', 'thana_name'=>'কমলগঞ্জ', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'46', 'thana_name'=>'কুলাউরা', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'46', 'thana_name'=>'মৌলভীবাজার সদর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'46', 'thana_name'=>'রাজনগর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'46', 'thana_name'=>'শ্রীমঙ্গল', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'47', 'thana_name'=>'বিশশসরপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'47', 'thana_name'=>'ছাতক', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'47', 'thana_name'=>'ধীরাই চাঁদপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'47', 'thana_name'=>'দুয়ারা বাজার', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'47', 'thana_name'=>'ঘুঙ্গিয়ার', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'47', 'thana_name'=>'জগন্নাথপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'47', 'thana_name'=>'শচনা', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'47', 'thana_name'=>'সুনামগঞ্জ সদর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'47', 'thana_name'=>'তাহিরপুর', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")],
            ['district_id'=>'48', 'thana_name'=>'বালাগঞ্জ', 'created_at' => strftime("%Y-%m-%d %H:%M:%S"), 'updated_at' => strftime("%Y-%m-%d %H:%M:%S")]
        ];

        
        DB::table("thanas")->insert($thanas);
    }
}
